version: "3.1"

services:
  web:
    container_name: "laravel-web"
    build:
      context: ./laravel-api
      dockerfile: ./Dockerfile.yml
    env_file:
      - ./laravel-api/.env
    ports:
      - "8000:80"
    volumes:
      - ./laravel-api:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
      MYSQL_DATABASE: laravel

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
